---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: api-service-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: worker-service-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-service-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: api-service-account
  namespace: default
roleRef:
  kind: Role
  name: api-service-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: worker-service-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: worker-service-account
  namespace: default
roleRef:
  kind: Role
  name: worker-service-role
  apiGroup: rbac.authorization.k8s.io