apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../manifests

namespace: dev

namePrefix: dev-

resources:
- namespace.yaml

patchesStrategicMerge:
- deployment-patch.yaml

images:
- name: ghcr.io/your-org/your-repo-api
  newName: ghcr.io/your-org/your-repo-api
  newTag: develop
- name: ghcr.io/your-org/your-repo-worker
  newName: ghcr.io/your-org/your-repo-worker
  newTag: develop